# Site settings
title: Orlewilson Bentes Maia
description: >- # this means to ignore newlines until "baseurl:"
  Professor - Pesquisador - Mentor - Consultor - Palestrante - Arduino - Internet das Coisas (IoT) - Metodologias Ativas - Programação Orientada a Objetos - Python - Programação Web - Git - Qualidade de Experiência (Quality of Experience - QoE) - Garantia de Qualidade (Quality Assurance - QA)
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://orlewilson.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed

# Author Info
author:
  name          : Orlewilson Bentes Maia
  image         : img/profile.png
# behance       : your_username
# dribbble      : your_username
  email         : prof.orlewilson@gmail.com
  facebook      : orlewilsonmaia
  github        : orlewilson
# gitlab        : your_username
  instagram     : orlewilson
  linkedin      : orlewilson
# medium        : orlewilson
# soundcloud    : your_username
# spotify       : your_username
# stackoverflow : your_user_id
# tumblr        : your_username.tumblr.com
# twitch        : your_username
  twitter       : orlewilson
# vimeo         : your_username
  youtube       : channel/UCrmTzjmyiezVxQYpDFHD-9A

# Collections
collections:
  experiences:
    output: true
    permalink: /experiences/:name
  classes:
    output: true
    permalink: /classes/:name
  mentoring:
    output: true
    permalink: /mentoring/:name
  events:
    output: true
    permalink: /events/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "mentoring"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "page"


# Posts default Permalink
#permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock